name: Create native distributions

on:  
  release:
    types: [published]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Build Linux Native x86-64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Build binary
        run: ./gradlew build
      
      - name: Find and copy package to current folder
        run: |
          cp $(find ./build/bin/native/releaseExecutable/ -type f -iname "*") ./textvar_linux_x86-64
        shell: bash
        
      - name: Upload package to Github release page
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'textvar_linux_x86-64'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}
        
  buildWindows: 
    runs-on: windows-latest
    
    name: Build Windows Native x86-64
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      
      - name: Build package
        run: ./gradlew.bat build
        
      - name: Find and copy package to current folder
        run: |
          cp $(find ./build/bin/native/releaseExecutable/ -type f -iname "*.exe") ./textvar_x86-64.exe
        shell: bash
        
      - name: Upload package to Github release page
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'textvar_x86-64.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}

  buildMacOS:
    # The type of runner that the job will run on
    runs-on: macos-latest

    name: Build MacOS Native x86-64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Build package
        run: ./gradlew build
      
      - name: List native build
        run: |
          ls ./build/bin/native/releaseExecutable/ 
        shell: bash

      - name: Find and copy package to current folder
        run: |
          cp $(find ./build/bin/native/releaseExecutable/ -type f -iname "*") ./textvar_macos_x86-64
        shell: bash
        
      - name: Upload package to Github release page
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'textvar_macos_x86-64'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}
      
